### ISSUE TITLE
Can't access data in bucket S3 subdirectories

### ISSUE THREAD

**Issue by Uyenkim1990** [aws-samples/dbt-glue#172] opened 2023-04-25 13:22 UTC
### Describe the bug
We have a table in Glue catalog which is related to a location that contains subdirectories. For example, the location is: s3://bucket/event-ingest, but the parquet files are in the subdirectories s3://bucket/event-ingest/2023/04/11/15. When we used the command "dbt run", it is executed successfully and the target table is created, but there are no rows inside. When we copy the parquet files in the root folder, the rows are well loaded in the target table.

### Expected behavior
dbt-glue can read source table with files located in subdirectories of a S3 bucket.

### Screenshots and log output
The profiles.yml:
![image](https://user-images.githubusercontent.com/88731929/234286688-69e0737b-b88e-4cec-8662-72fdb686bbfb.png)

The table setting in Glue:
![image](https://user-images.githubusercontent.com/88731929/234287039-0b6ef28a-896c-409b-9253-d8fb71aa0c04.png)

The bucket S3:
![image](https://user-images.githubusercontent.com/88731929/234287407-839947d5-f5bc-469f-9b4d-6f91ac0ff790.png)

The dbt output:
![image](https://user-images.githubusercontent.com/88731929/234287709-8297a728-caf4-42f2-b14d-3a2a2793b031.png)

The target table after dbt execution:
![image](https://user-images.githubusercontent.com/88731929/234289087-c7f56487-111f-4742-b67c-541c0629f929.png)

### System information
**The output of `dbt --version`:**
```
Core:
  - installed: 1.4.5
 Plugins:
  - glue:  1.4.1
  - spark: 1.4.1
```

**The operating system we are using:**
Windows 10
**The output of `python --version`:**
Python 3.9.7

**Comment by rickiesmooth** [comment] 2023-08-22 20:46
is your glue table partitioned?

**Comment by moomindani** [comment] 2024-02-01 04:17
Closing this since we are not able to reproduce.

**Closed by moomindani** 2024-02-01 04:17 UTC
Labels: bug
